### ISSUE TITLE
load model problem

### ISSUE THREAD

**Issue by grzegorzewskiflyingdog** [stablecabal/gyre#1]
When i try to start the server(newest version 02.02.2023) it starts to load some model but then i got an error:
 File "/gyre/manager.py", line 1398, in _load_from_weight_candidates
    raise EnvironmentError(
OSError: Failed to load model stability-vae-ema. Failed attempts:
  - Error when trying to load weights from /weights/sd-vae-ft-ema-fp16. Error no file named diffusion_pytorch_model.bin found in directory /weights/sd-vae-ft-ema-fp16.
  - Error when trying to load weights from /weights/sd-vae-ft-ema. Error no file named diffusion_pytorch_model.bin found in directory /weights/sd-vae-ft-ema.
  - Couldn't query local HuggingFace cache.[Errno 2] No such file or directory: '/huggingface/hub/models--stabilityai--sd-vae-ft-ema/refs/main'
  - No URL was provided
  - Downloading from HuggingFace failed.'.ckpt'

In previous version (few days before) there was no such problem

**Comment by hafriedlander** [comment]
This should be fixed by https://github.com/stablecabal/gyre/commit/cf87127c1f139cc42117dcf21f5e1adb811d28bc

**Comment by hafriedlander** [comment]
Hi. I believe this is fixed. Please reopen if you are still experiencing in latest stable.
