### ISSUE TITLE
change %USERPROFILE%/.cache location

### ISSUE THREAD

**Issue by Firsto** [stablecabal/gyre#5]
is there any config to change default cache location, except moving user folder from system disk?

**Comment by Firsto** [comment]
i have tried to change path in `gyre/gyre/constants.py` but it returns back after launch installer

**Comment by hafriedlander** [comment]
You can set the XDG_CACHE_PATH variable in your environment. If using gyre-installer, add it as a new line to your `config` file (anything in the config file is added to the environment)

You can alternatively set the SD_HOME and HF_HOME environment variables to control just where Gyre and HuggingFace store their models respectively. These are set by default to ${XDG_CACHE_PATH}/gyre and ${XDG_CACHE_PATH}/huggingface/hub.
