### ISSUE TITLE
How to change BaseModel now?

### ISSUE THREAD

**Issue by sdbds** [stablecabal/gyre#6]
Has this feature been completed? I noticed there are other models in the config, but I haven't found how to access them on the UI yet.

**Comment by imperator-maximus** [comment]
yes there are some models  in configuration already available and just needed to activate:
SD_ENGINECFG_1={id: "reality-engine", enabled: True}
SD_ENGINECFG_2={id: "deliberate", enabled: True}

It is also possible to load a model directly by config parameter. It needs a fragment. example:
SD_ENGINECFG_1='!stable-diffusion-v1-5-ckpt/lyriel { "name": "lyriel", "enabled": True, "source": { "model" : "https://civitai.com/api/download/models/50127" } }'

after restart these should be available in frontend

**Comment by sdbds** [comment]
> yes there are some models in configuration already available and just needed to activate: SD_ENGINECFG_1={id: "reality-engine", enabled: True} SD_ENGINECFG_2={id: "deliberate", enabled: True}
> 
> It is also possible to load a model directly by config parameter. It needs a fragment. example: SD_ENGINECFG_1='!stable-diffusion-v1-5-ckpt/lyriel { "name": "lyriel", "enabled": True, "source": { "model" : "https://civitai.com/api/download/models/50127" } }'
> 
> after restart these should be available in frontend

thank u for replying！i found template such as this but nothing about local model.
i dont want to download with huggingface in default .cache,
can i use this way to add localmodel?

SD_ENGINECFG_1='!stable-diffusion-v1-5-ckpt/lyriel { "name": "lyriel", "enabled": True, "source": { "local_model" : "D:\models\lyriel.ckpt" } }'

**Comment by hafriedlander** [comment]
Yes, that will work, but two changes:
- use `/` slashes rather than `\`
- The ckpt should be in it's own folder (in this case, the file would be d:\models\lyriel\lyriel.ckpt)

`SD_ENGINECFG_1='!stable-diffusion-v1-5-ckpt/lyriel { "name": "lyriel", "enabled": True, "source": { "local_model" : "D:/models/lyriel" } }'`

Specifying the exact path to the ckpt won't work at the moment, but I'll add it to the TODO for a future release, since a few people have asked for it.

**Comment by sdbds** [comment]
> Yes, that will work, but two changes:
> 
> * use `/` slashes rather than `\`
> * The ckpt should be in it's own folder (in this case, the file would be d:\models\lyriel\lyriel.ckpt)
> 
> `SD_ENGINECFG_1='!stable-diffusion-v1-5-ckpt/lyriel { "name": "lyriel", "enabled": True, "source": { "local_model" : "D:/models/lyriel" } }'`
> 
> Specifying the exact path to the ckpt won't work at the moment, but I'll add it to the TODO for a future release, since a few people have asked for it.

thank u,i got it!
